// Date: 11/11/2014 2:16:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelAnomalocaris extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Head;
    ModelRenderer Eyeleft;
    ModelRenderer EyeRight;
    ModelRenderer butt;
    ModelRenderer armLeftA;
    ModelRenderer armLeftB;
    ModelRenderer armLeftC;
    ModelRenderer armRightA;
    ModelRenderer armRightB;
    ModelRenderer armRightC;
    ModelRenderer Left1;
    ModelRenderer Left2;
    ModelRenderer Left3;
    ModelRenderer Left4;
    ModelRenderer Left5;
    ModelRenderer Left6;
    ModelRenderer Left7;
    ModelRenderer Left8;
    ModelRenderer Left9;
    ModelRenderer Left10;
    ModelRenderer Left11;
    ModelRenderer Right1;
    ModelRenderer Right2;
    ModelRenderer Right3;
    ModelRenderer Right4;
    ModelRenderer Right5;
    ModelRenderer Right6;
    ModelRenderer Right7;
    ModelRenderer Right8;
    ModelRenderer Right9;
    ModelRenderer Right10;
    ModelRenderer Right11;
    ModelRenderer LeftWing1;
    ModelRenderer LeftWing2;
    ModelRenderer LeftWing3;
    ModelRenderer LeftWing4;
    ModelRenderer LeftWing5;
    ModelRenderer RightWing1;
    ModelRenderer RightWing2;
    ModelRenderer RightWing3;
    ModelRenderer RightWing4;
    ModelRenderer RightWing5;
    ModelRenderer LeftTail;
    ModelRenderer RightTail;
  
  public ModelAnomalocaris()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 46);
      Body.addBox(-2F, -1F, 0F, 4, 3, 14);
      Body.setRotationPoint(-1F, 6F, 0F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 37);
      Head.addBox(-3F, -1F, -6F, 4, 2, 6);
      Head.setRotationPoint(0F, 6F, 0F);
      Head.setTextureSize(128, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Eyeleft = new ModelRenderer(this, 25, 41);
      Eyeleft.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      Eyeleft.setRotationPoint(0.5F, 5.5F, -5.5F);
      Eyeleft.setTextureSize(128, 64);
      Eyeleft.mirror = true;
      setRotation(Eyeleft, 0.122173F, 0.3490659F, 0.8726646F);
      EyeRight = new ModelRenderer(this, 25, 41);
      EyeRight.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      EyeRight.setRotationPoint(-2.5F, 5.5F, -5.5F);
      EyeRight.setTextureSize(128, 64);
      EyeRight.mirror = true;
      setRotation(EyeRight, 0.122173F, -0.3490659F, -0.8726646F);
      butt = new ModelRenderer(this, 42, 30);
      butt.addBox(-1.466667F, -1F, 0F, 3, 3, 5);
      butt.setRotationPoint(-1F, 6F, 14F);
      butt.setTextureSize(128, 64);
      butt.mirror = true;
      setRotation(butt, 0F, 0F, 0F);
      armLeftA = new ModelRenderer(this, 36, 41);
      armLeftA.addBox(-0.4F, -0.5F, -0.5F, 1, 3, 1);
      armLeftA.setRotationPoint(0.5F, 6.5F, -6F);
      armLeftA.setTextureSize(128, 64);
      armLeftA.mirror = true;
      setRotation(armLeftA, -1.256637F, 0F, 0F);
      armLeftB = new ModelRenderer(this, 21, 35);
      armLeftB.addBox(-0.5F, 1.3F, -2.1F, 1, 4, 1);
      armLeftB.setRotationPoint(0.5F, 6.5F, -6F);
      armLeftB.setTextureSize(128, 64);
      armLeftB.mirror = true;
      setRotation(armLeftB, -0.4363323F, 0F, 0F);
      armLeftC = new ModelRenderer(this, 36, 36);
      armLeftC.addBox(-0.6F, 0F, -5.7F, 1, 3, 1);
      armLeftC.setRotationPoint(0.5F, 6.5F, -6F);
      armLeftC.setTextureSize(128, 64);
      armLeftC.mirror = true;
      setRotation(armLeftC, 0.7679449F, 0F, 0F);
      armRightA = new ModelRenderer(this, 36, 41);
      armRightA.addBox(-0.6F, -0.5F, -0.5F, 1, 3, 1);
      armRightA.setRotationPoint(-2.5F, 6.5F, -6F);
      armRightA.setTextureSize(128, 64);
      armRightA.mirror = true;
      setRotation(armRightA, -1.256637F, 0F, 0F);
      armRightB = new ModelRenderer(this, 21, 35);
      armRightB.addBox(-0.5F, 1.3F, -2.1F, 1, 4, 1);
      armRightB.setRotationPoint(-2.5F, 6.5F, -6F);
      armRightB.setTextureSize(128, 64);
      armRightB.mirror = true;
      setRotation(armRightB, -0.4363323F, 0F, 0F);
      armRightC = new ModelRenderer(this, 36, 36);
      armRightC.addBox(-0.4F, 0F, -5.7F, 1, 3, 1);
      armRightC.setRotationPoint(-2.5F, 6.5F, -6F);
      armRightC.setTextureSize(128, 64);
      armRightC.mirror = true;
      setRotation(armRightC, 0.7679449F, 0F, 0F);
      Left1 = new ModelRenderer(this, 0, 28);
      Left1.addBox(0F, 0F, 0F, 5, 1, 1);
      Left1.setRotationPoint(0F, 6F, 0F);
      Left1.setTextureSize(128, 64);
      Left1.mirror = true;
      setRotation(Left1, 0F, 0F, 0.1745329F);
      Left2 = new ModelRenderer(this, 0, 26);
      Left2.addBox(0F, 0F, 0F, 6, 1, 1);
      Left2.setRotationPoint(0F, 6F, 1F);
      Left2.setTextureSize(128, 64);
      Left2.mirror = true;
      setRotation(Left2, 0F, 0F, 0.1047198F);
      Left3 = new ModelRenderer(this, 0, 24);
      Left3.addBox(0F, 0F, 0F, 7, 1, 1);
      Left3.setRotationPoint(0F, 6F, 2F);
      Left3.setTextureSize(128, 64);
      Left3.mirror = true;
      setRotation(Left3, 0F, 0F, 0.0349066F);
      Left4 = new ModelRenderer(this, 0, 22);
      Left4.addBox(0F, 0F, 0F, 8, 1, 1);
      Left4.setRotationPoint(0F, 6F, 3F);
      Left4.setTextureSize(128, 64);
      Left4.mirror = true;
      setRotation(Left4, 0F, 0F, -0.0349066F);
      Left5 = new ModelRenderer(this, 0, 20);
      Left5.addBox(0F, 0F, 0F, 9, 1, 1);
      Left5.setRotationPoint(0F, 6F, 4F);
      Left5.setTextureSize(128, 64);
      Left5.mirror = true;
      setRotation(Left5, 0F, 0F, -0.1047198F);
      Left6 = new ModelRenderer(this, 0, 18);
      Left6.addBox(0F, 0F, 0F, 9, 1, 1);
      Left6.setRotationPoint(0F, 6F, 5F);
      Left6.setTextureSize(128, 64);
      Left6.mirror = true;
      setRotation(Left6, 0F, 0F, -0.1745329F);
      Left7 = new ModelRenderer(this, 0, 16);
      Left7.addBox(0F, 0F, 0F, 9, 1, 1);
      Left7.setRotationPoint(0F, 6F, 6F);
      Left7.setTextureSize(128, 64);
      Left7.mirror = true;
      setRotation(Left7, 0F, 0F, -0.1570796F);
      Left8 = new ModelRenderer(this, 0, 14);
      Left8.addBox(0F, 0F, 0F, 8, 1, 1);
      Left8.setRotationPoint(0F, 6F, 7F);
      Left8.setTextureSize(128, 64);
      Left8.mirror = true;
      setRotation(Left8, 0F, 0F, -0.1047198F);
      Left9 = new ModelRenderer(this, 0, 12);
      Left9.addBox(0F, 0F, 0F, 7, 1, 1);
      Left9.setRotationPoint(0F, 6F, 8F);
      Left9.setTextureSize(128, 64);
      Left9.mirror = true;
      setRotation(Left9, 0F, 0F, -0.0349066F);
      Left10 = new ModelRenderer(this, 0, 10);
      Left10.addBox(0F, 0F, 0F, 6, 1, 1);
      Left10.setRotationPoint(0F, 6F, 9F);
      Left10.setTextureSize(128, 64);
      Left10.mirror = true;
      setRotation(Left10, 0F, 0F, 0.0349066F);
      
      Left11 = new ModelRenderer(this, 0, 8);
      Left11.addBox(0F, 0F, 0F, 5, 1, 1);
      Left11.setRotationPoint(0F, 6F, 10F);
      Left11.setTextureSize(128, 64);
      Left11.mirror = true;
      setRotation(Left11, 0F, 0F, 0.1047198F);

      Right1 = new ModelRenderer(this, 22, 28);
      Right1.addBox(-5F, 0F, 0F, 5, 1, 1);
      Right1.setRotationPoint(-2F, 6F, 0F);
      Right1.setTextureSize(128, 64);
      Right1.mirror = true;
      setRotation(Right1, 0F, 0F, -0.1745329F);

      Right2 = new ModelRenderer(this, 22, 26);
      Right2.addBox(-6F, 0F, 0F, 6, 1, 1);
      Right2.setRotationPoint(-2F, 6F, 1F);
      Right2.setTextureSize(128, 64);
      Right2.mirror = true;
      setRotation(Right2, 0F, 0F, -0.1047198F);
      
      Right3 = new ModelRenderer(this, 22, 24);
      Right3.addBox(-7F, 0F, 0F, 7, 1, 1);
      Right3.setRotationPoint(-2F, 6F, 2F);
      Right3.setTextureSize(128, 64);
      Right3.mirror = true;
      setRotation(Right3, 0F, 0F, -0.0349066F);

      Right4 = new ModelRenderer(this, 22, 22);
      Right4.addBox(-8F, 0F, 0F, 8, 1, 1);
      Right4.setRotationPoint(-2F, 6F, 3F);
      Right4.setTextureSize(128, 64);
      Right4.mirror = true;
      setRotation(Right4, 0F, 0F, 0.0349066F);
 
      Right5 = new ModelRenderer(this, 22, 20);
      Right5.addBox(-9F, 0F, 0F, 9, 1, 1);
      Right5.setRotationPoint(-2F, 6F, 4F);
      Right5.setTextureSize(128, 64);
      Right5.mirror = true;
      setRotation(Right5, 0F, 0F, 0.1047198F);
  
      Right6 = new ModelRenderer(this, 22, 18);
      Right6.addBox(-9F, 0F, 0F, 9, 1, 1);
      Right6.setRotationPoint(-2F, 6F, 5F);
      Right6.setTextureSize(128, 64);
      Right6.mirror = true;
      setRotation(Right6, 0F, 0F, 0.1745329F);
    
      Right7 = new ModelRenderer(this, 22, 16);
      Right7.addBox(-9F, 0F, 0F, 9, 1, 1);
      Right7.setRotationPoint(-2F, 6F, 6F);
      Right7.setTextureSize(128, 64);
      Right7.mirror = true;
      setRotation(Right7, 0F, 0F, 0.1570796F);
     
      Right8 = new ModelRenderer(this, 22, 14);
      Right8.addBox(-8F, 0F, 0F, 8, 1, 1);
      Right8.setRotationPoint(-2F, 6F, 7F);
      Right8.setTextureSize(128, 64);
      Right8.mirror = true;
      setRotation(Right8, 0F, 0F, 0.1047198F);
     
      Right9 = new ModelRenderer(this, 22, 12);
      Right9.addBox(-7F, 0F, 0F, 7, 1, 1);
      Right9.setRotationPoint(-2F, 6F, 8F);
      Right9.setTextureSize(128, 64);
      Right9.mirror = true;
      setRotation(Right9, 0F, 0F, 0.0349066F);
    
      Right10 = new ModelRenderer(this, 22, 10);
      Right10.addBox(-6F, 0F, 0F, 6, 1, 1);
      Right10.setRotationPoint(-2F, 6F, 9F);
      Right10.setTextureSize(128, 64);
      Right10.mirror = true;
      setRotation(Right10, 0F, 0F, -0.0349066F);
      
      Right11 = new ModelRenderer(this, 22, 8);
      Right11.addBox(-5F, 0F, 0F, 5, 1, 1);
      Right11.setRotationPoint(-2F, 6F, 10F);
      Right11.setTextureSize(128, 64);
      Right11.mirror = true;
      setRotation(Right11, 0F, 0F, -0.1047198F);
     
      LeftWing1 = new ModelRenderer(this, 37, 61);
      LeftWing1.addBox(0F, 0F, 0F, 3, 1, 1);
      LeftWing1.setRotationPoint(0F, 5F, 14F);
      LeftWing1.setTextureSize(128, 64);
      LeftWing1.mirror = true;
      setRotation(LeftWing1, 0F, 0F, -0.4886922F);
      LeftWing2 = new ModelRenderer(this, 37, 59);
      LeftWing2.addBox(0F, 0F, 0F, 4, 1, 1);
      LeftWing2.setRotationPoint(0F, 5F, 15F);
      LeftWing2.setTextureSize(128, 64);
      LeftWing2.mirror = true;
      setRotation(LeftWing2, 0F, 0F, -0.5235988F);
      LeftWing3 = new ModelRenderer(this, 37, 57);
      LeftWing3.addBox(0F, 0F, 0F, 5, 1, 1);
      LeftWing3.setRotationPoint(0F, 5F, 16F);
      LeftWing3.setTextureSize(128, 64);
      LeftWing3.mirror = true;
      setRotation(LeftWing3, 0F, 0F, -0.5585054F);
      LeftWing4 = new ModelRenderer(this, 37, 55);
      LeftWing4.addBox(0F, 0F, 0F, 4, 1, 1);
      LeftWing4.setRotationPoint(0F, 5F, 17F);
      LeftWing4.setTextureSize(128, 64);
      LeftWing4.mirror = true;
      setRotation(LeftWing4, 0F, 0F, -0.4886922F);
      LeftWing5 = new ModelRenderer(this, 37, 53);
      LeftWing5.addBox(0F, 0F, 0F, 3, 1, 1);
      LeftWing5.setRotationPoint(0F, 5F, 18F);
      LeftWing5.setTextureSize(128, 64);
      LeftWing5.mirror = true;
      setRotation(LeftWing5, 0F, 0F, -0.3839724F);
      RightWing1 = new ModelRenderer(this, 37, 51);
      RightWing1.addBox(-3F, 0F, 0F, 3, 1, 1);
      RightWing1.setRotationPoint(-2F, 5F, 14F);
      RightWing1.setTextureSize(128, 64);
      RightWing1.mirror = true;
      setRotation(RightWing1, 0F, 0F, 0.4886922F);
      RightWing2 = new ModelRenderer(this, 37, 49);
      RightWing2.addBox(-4F, 0F, 0F, 4, 1, 1);
      RightWing2.setRotationPoint(-2F, 5F, 15F);
      RightWing2.setTextureSize(128, 64);
      RightWing2.mirror = true;
      setRotation(RightWing2, 0F, 0F, 0.5235988F);
      RightWing3 = new ModelRenderer(this, 37, 47);
      RightWing3.addBox(-5F, 0F, 0F, 5, 1, 1);
      RightWing3.setRotationPoint(-2F, 5F, 16F);
      RightWing3.setTextureSize(128, 64);
      RightWing3.mirror = true;
      setRotation(RightWing3, 0F, 0F, 0.5585054F);
      RightWing4 = new ModelRenderer(this, 41, 45);
      RightWing4.addBox(-4F, 0F, 0F, 4, 1, 1);
      RightWing4.setRotationPoint(-2F, 5F, 17F);
      RightWing4.setTextureSize(128, 64);
      RightWing4.mirror = true;
      setRotation(RightWing4, 0F, 0F, 0.4886922F);
      RightWing5 = new ModelRenderer(this, 41, 43);
      RightWing5.addBox(-3F, 0F, 0F, 3, 1, 1);
      RightWing5.setRotationPoint(-2F, 5F, 18F);
      RightWing5.setTextureSize(128, 64);
      RightWing5.mirror = true;
      setRotation(RightWing5, 0F, 0F, 0.3839724F);
      LeftTail = new ModelRenderer(this, 48, 27);
      LeftTail.addBox(-0.4666667F, -0.5F, 0F, 1, 1, 12);
      LeftTail.setRotationPoint(0F, 6F, 19F);
      LeftTail.setTextureSize(128, 64);
      LeftTail.mirror = true;
      setRotation(LeftTail, 0F, 0F, 0F);
      RightTail = new ModelRenderer(this, 48, 27);
      RightTail.addBox(-0.4666667F, -0.5F, 0F, 1, 1, 12);
      RightTail.setRotationPoint(-2F, 6F, 19F);
      RightTail.setTextureSize(128, 64);
      RightTail.mirror = true;
      setRotation(RightTail, 0F, 0F, 0F);
      convertToChild(armLeftB,armLeftC);
      convertToChild(armLeftA,armLeftB);
      convertToChild(armRightB,armRightC);
      convertToChild(armRightA,armRightB);
  }
  protected void convertToChild( ModelRenderer parParent,ModelRenderer parChild )
  {
     
     parChild.rotationPointX -= parParent.rotationPointX;
     parChild.rotationPointY -= parParent.rotationPointY;
     parChild.rotationPointZ -= parParent.rotationPointZ;
     parChild.rotateAngleX -= parParent.rotateAngleX;
     parChild.rotateAngleY -= parParent.rotateAngleY;
     parChild.rotateAngleZ -= parParent.rotateAngleZ;
     parParent.addChild(parChild);
  } 
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f, entity);
    Body.render(f5);
    Head.render(f5);
    Eyeleft.render(f5);
    EyeRight.render(f5);
    butt.render(f5);
    armLeftA.render(f5);
    armRightA.render(f5);
    Left1.render(f5);
    Left2.render(f5);
    Left3.render(f5);
    Left4.render(f5);
    Left5.render(f5);
    Left6.render(f5);
    Left7.render(f5);
    Left8.render(f5);
    Left9.render(f5);
    Left10.render(f5);
    Left11.render(f5);
    Right1.render(f5);
    Right2.render(f5);
    Right3.render(f5);
    Right4.render(f5);
    Right5.render(f5);
    Right6.render(f5);
    Right7.render(f5);
    Right8.render(f5);
    Right9.render(f5);
    Right10.render(f5);
    Right11.render(f5);
    LeftWing1.render(f5);
    LeftWing2.render(f5);
    LeftWing3.render(f5);
    LeftWing4.render(f5);
    LeftWing5.render(f5);
    RightWing1.render(f5);
    RightWing2.render(f5);
    RightWing3.render(f5);
    RightWing4.render(f5);
    RightWing5.render(f5);
    LeftTail.render(f5);
    RightTail.render(f5);
   

  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    armLeftA.rotateAngleX = -0.2F * MathHelper.sin(f2 * (float)0.35F + f1)-1.256637F;
    armRightA.rotateAngleX = -0.2F * MathHelper.sin(f2 * (float)0.35F + f1)-1.256637F;


    

    
    LeftTail.rotateAngleY = -0.01F * MathHelper.sin(f2 * (float)0.35F + f1);
    RightTail.rotateAngleY = 0.01F * MathHelper.sin(f2 * (float)0.35F + f1);
    LeftTail.rotateAngleX = 0.01F * MathHelper.sin(f2 * (float)0.35F + f1);
    RightTail.rotateAngleX = -0.01F * MathHelper.sin(f2 * (float)0.35F + f1);
  }

  
}
