// Date: 9/17/2014 7:35:03 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelCephalaspis extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer body;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer tail3;
  
  public ModelCephalaspis()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, -2.4F, 0F, 5, 4, 5);
      Head.setRotationPoint(0F, 22.5F, -7F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, -0.7853982F, 0F);
      body = new ModelRenderer(this, 0, 13);
      body.addBox(-2F, 0F, 0F, 4, 3, 4);
      body.setRotationPoint(0F, 21F, -2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 0, 9);
      Arm1.addBox(0F, 0F, 0F, 1, 1, 3);
      Arm1.setRotationPoint(2.5F, 22F, -3.5F);
      Arm1.setTextureSize(64, 32);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 0, 9);
      Arm2.addBox(-1F, 0F, 0F, 1, 1, 3);
      Arm2.setRotationPoint(-2.5F, 22F, -3.4F);
      Arm2.setTextureSize(64, 32);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, 0F);
      tail1 = new ModelRenderer(this, 0, 20);
      tail1.addBox(-1F, -1F, 0F, 2, 2, 4);
      tail1.setRotationPoint(0F, 23F, 2F);
      tail1.setTextureSize(64, 32);
      tail1.mirror = true;
      setRotation(tail1, 0F, 0F, 0F);
      tail2 = new ModelRenderer(this, 56, 0);
      tail2.addBox(-0.5F, 2F, 2.5F, 1, 1, 3);
      tail2.setRotationPoint(0F, 23F, 2F);
      tail2.setTextureSize(64, 32);
      tail2.mirror = true;
      setRotation(tail2, 0.7853982F, 0F, 0F);
      tail3 = new ModelRenderer(this, 56, 0);
      tail3.addBox(0F, 3F, 1.5F, 0, 2, 4);
      tail3.setRotationPoint(0F, 23F, 2F);
      tail3.setTextureSize(64, 32);
      tail3.mirror = true;
      setRotation(tail3, 0.7853982F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    body.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    tail3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    this.tail1.rotateAngleY = 0.2F * MathHelper.sin(f2 * (float)0.35F + f1);
    this.tail2.rotateAngleY = this.tail1.rotateAngleY;
    this.tail3.rotateAngleY = this.tail1.rotateAngleY;

  }

}
