// Date: 9/9/2014 8:49:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPikaia extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Tail1;
    ModelRenderer Neck1;
    ModelRenderer Tail2;
    ModelRenderer Tailfin1;
    ModelRenderer Tailfin2;
    ModelRenderer Head;
    ModelRenderer Eyestalk1;
    ModelRenderer Eyestalk2;
  
  public ModelPikaia()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 22, 25);
      Body.addBox(-1.5F, 0F, 0F, 3, 2, 5);
      Body.setRotationPoint(0F, 13F, 0F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 23, 33);
      Tail1.addBox(-1.5F, -1F, 0F, 3, 3, 4);
      Tail1.setRotationPoint(0F, 13.5F, 4F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 24, 19);
      Neck1.addBox(-1F, -1F, -3F, 2, 2, 3);
      Neck1.setRotationPoint(0F, 14F, 0.5F);
      Neck1.setTextureSize(64, 64);
      Neck1.mirror = true;
      setRotation(Neck1, -0.1396263F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 25, 40);
      Tail2.addBox(-1F, 0F, 0F, 2, 2, 3);
      Tail2.setRotationPoint(0F, 13F, 7F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, -0.0743572F, 0F, 0F);
      Tailfin1 = new ModelRenderer(this, 16, 41);
      Tailfin1.addBox(0F, -1F, -1F, 0, 1, 4);
      Tailfin1.setRotationPoint(0F, 13F, 7F);
      Tailfin1.setTextureSize(64, 64);
      Tailfin1.mirror = true;
      setRotation(Tailfin1, -0.1487144F, 0F, 0F);
      Tailfin2 = new ModelRenderer(this, 36, 41);
      Tailfin2.addBox(0F, 2F, -1.5F, 0, 1, 4);
      Tailfin2.setRotationPoint(0F, 13F, 7F);
      Tailfin2.setTextureSize(64, 64);
      Tailfin2.mirror = true;
      setRotation(Tailfin2, 0.1487144F, 0F, 0F);
      Head = new ModelRenderer(this, 23, 13);
      Head.addBox(-1F, -1F, -3F, 2, 2, 3);
      Head.setRotationPoint(0F, 13.6F, -2F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, -0.0743572F, 0F, 0F);
      Eyestalk1 = new ModelRenderer(this, 31, 9);
      Eyestalk1.addBox(0F, -2F, 0F, 1, 2, 1);
      Eyestalk1.setRotationPoint(0.5F, 13F, -5F);
      Eyestalk1.setTextureSize(64, 64);
      Eyestalk1.mirror = true;
      setRotation(Eyestalk1, 0.8922867F, -0.7063936F, 0.5205006F);
      Eyestalk2 = new ModelRenderer(this, 23, 9);
      Eyestalk2.addBox(-1F, -2F, 0F, 1, 2, 1);
      Eyestalk2.setRotationPoint(-0.5F, 13F, -5F);
      Eyestalk2.setTextureSize(64, 64);
      Eyestalk2.mirror = true;
      setRotation(Eyestalk2, 0.8922867F, 0.7063936F, -0.5205006F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    Tail1.render(f5);
    Neck1.render(f5);
    Tail2.render(f5);
    Tailfin1.render(f5);
    Tailfin2.render(f5);
    Head.render(f5);
    Eyestalk1.render(f5);
    Eyestalk2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    this.Tail2.rotateAngleY = 0.2F * MathHelper.sin(f2 * (float)0.35F + f1);
	
	  this.Tailfin1.rotateAngleZ = this.Tail2.rotateAngleZ;
	  this.Tailfin1.rotateAngleY = this.Tail2.rotateAngleY;
	  this.Tailfin1.rotateAngleX = this.Tail2.rotateAngleX;
	  this.Tailfin2.rotateAngleZ = this.Tail2.rotateAngleZ;
	  this.Tailfin2.rotateAngleY = this.Tail2.rotateAngleY;
	  this.Tailfin2.rotateAngleX = this.Tail2.rotateAngleX;
  }

}
