// Date: 9/13/2014 7:54:34 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCyclonema extends ModelBase
{
  //fields
    ModelRenderer Shell1;
    ModelRenderer Body;
    ModelRenderer Shell2;
    ModelRenderer Shell3;
    ModelRenderer LeftAntenna;
    ModelRenderer RightAntenna;
  
  public ModelCyclonema()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shell1 = new ModelRenderer(this, 0, 17);
      Shell1.addBox(-2F, 0F, -2F, 4, 4, 3);
      Shell1.setRotationPoint(0F, 20.6F, 0F);
      Shell1.setTextureSize(64, 32);
      Shell1.mirror = true;
      setRotation(Shell1, 1.041001F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 2);
      Body.addBox(-1.5F, 1F, -2.2F, 3, 2, 4);
      Body.setRotationPoint(0F, 21F, 1F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Shell2 = new ModelRenderer(this, 2, 12);
      Shell2.addBox(-1.5F, 0.5F, 1F, 3, 3, 2);
      Shell2.setRotationPoint(0F, 20.6F, 0F);
      Shell2.setTextureSize(64, 32);
      Shell2.mirror = true;
      setRotation(Shell2, 1.041001F, 0F, 0F);
      Shell3 = new ModelRenderer(this, 3, 8);
      Shell3.addBox(-1F, 1F, 3F, 2, 2, 2);
      Shell3.setRotationPoint(0F, 20.6F, 0F);
      Shell3.setTextureSize(64, 32);
      Shell3.mirror = true;
      setRotation(Shell3, 1.041001F, 0F, 0F);
      LeftAntenna = new ModelRenderer(this, 0, 0);
      LeftAntenna.addBox(0F, -2F, 0F, 1, 2, 1);
      LeftAntenna.setRotationPoint(1F, 23F, -1F);
      LeftAntenna.setTextureSize(64, 32);
      LeftAntenna.mirror = true;
      setRotation(LeftAntenna, 0.8551081F, -0.5205006F, 0F);
      RightAntenna = new ModelRenderer(this, 0, 0);
      RightAntenna.addBox(-1F, -2F, 0F, 1, 2, 1);
      RightAntenna.setRotationPoint(-1F, 23F, -1F);
      RightAntenna.setTextureSize(64, 32);
      RightAntenna.mirror = true;
      setRotation(RightAntenna, 0.8551081F, 0.5205006F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shell1.render(f5);
    Body.render(f5);
    Shell2.render(f5);
    Shell3.render(f5);
    LeftAntenna.render(f5);
    RightAntenna.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
