// Date: 9/7/2014 3:48:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelArandaspidis extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer Body;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
  
  public ModelArandaspidis()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-2.5F, -2.5F, -8F, 5, 5, 8);
      head.setRotationPoint(0F, 21.5F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 26, 0);
      Body.addBox(-1.5F, -2F, 0F, 3, 4, 3);
      Body.setRotationPoint(0F, 21.5F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 38, 0);
      Tail1.addBox(-1F, -1.5F, 0F, 2, 3, 5);
      Tail1.setRotationPoint(0F, 21.5F, 3F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 52, 0);
      Tail2.addBox(-0.5F, -1F, 5F, 1, 2, 4);
      Tail2.setRotationPoint(0F, 21.5F, 3F);
      Tail2.setTextureSize(64, 32);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 42, 9);
      Tail3.addBox(0F, -2F, 6F, 0, 4, 5);
      Tail3.setRotationPoint(0F, 21.5F, 3F);
      Tail3.setTextureSize(64, 32);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    Body.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    this.Tail1.rotateAngleZ = 0F;
	  this.head.rotateAngleZ = 0F; 
	  this.Tail1.rotateAngleY = 0.2F * MathHelper.sin(f2 * (float)0.35F + f1);
	  this.Tail2.rotateAngleZ = this.Tail1.rotateAngleZ;
	  this.Tail2.rotateAngleY = this.Tail1.rotateAngleY;
	  this.Tail2.rotateAngleX = this.Tail1.rotateAngleX;
	  this.Tail3.rotateAngleZ = this.Tail1.rotateAngleZ;
	  this.Tail3.rotateAngleY = this.Tail1.rotateAngleY;
	  this.Tail3.rotateAngleX = this.Tail1.rotateAngleX;
  }

}
