// Date: 10/8/2014 6:03:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFishBowl extends ModelBase
{
  //fields
    ModelRenderer Tank;
    ModelRenderer Sand;
    ModelRenderer Water;
    ModelRenderer Top;
  
  public ModelFishBowl()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Tank = new ModelRenderer(this, 0, 0);
      Tank.addBox(-8F, 0F, -8F, 16, 14, 16);
      Tank.setRotationPoint(0F, 10.1F, 0F);
      Tank.setTextureSize(64, 128);
      Tank.mirror = true;
      setRotation(Tank, 0F, 0F, 0F);
      Sand = new ModelRenderer(this, 0, 31);
      Sand.addBox(-7.5F, 0F, -7.5F, 15, 1, 15);
      Sand.setRotationPoint(0F, 23F, 0F);
      Sand.setTextureSize(64, 128);
      Sand.mirror = true;
      setRotation(Sand, 0F, 0F, 0F);
      Water = new ModelRenderer(this, 0, 48);
      Water.addBox(-7.5F, 0F, -7.6F, 15, 12, 15);
      Water.setRotationPoint(0F, 12F, 0F);
      Water.setTextureSize(64, 128);
      Water.mirror = true;
      setRotation(Water, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 76);
      Top.addBox(-5F, 0F, -5F, 10, 2, 10);
      Top.setRotationPoint(0F, 8.1F, 0F);
      Top.setTextureSize(64, 128);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Tank.render(f5);
    Sand.render(f5);
    Top.render(f5);

    GL11.glEnable(GL11.GL_BLEND);
    GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
    Water.render(f5);
    GL11.glDisable(GL11.GL_BLEND);
  }
  public void renderModel(float f5){
	  Tank.render(f5);
	    Sand.render(f5);
	    Top.render(f5);
	    
	    GL11.glEnable(GL11.GL_BLEND);
        GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
	    Water.render(f5);
        GL11.glDisable(GL11.GL_BLEND);
	    }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
