// Date: 8/11/2014 6:06:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelHaikouichthys  extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer bodyfin;
    ModelRenderer tail;
    ModelRenderer tailfin;
  
  public ModelHaikouichthys ()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 14, 0);
      head.addBox(-1F, -1F, -2F, 2, 2, 2);
      head.setRotationPoint(0F, 23F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-1.5F, -1.5F, 0F, 3, 3, 4);
      body.setRotationPoint(0F, 23F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      bodyfin = new ModelRenderer(this, 22, 0);
      bodyfin.addBox(0F, -2.8F, 0F, 0, 2, 4);
      bodyfin.setRotationPoint(0F, 23F, 0F);
      bodyfin.setTextureSize(64, 32);
      bodyfin.mirror = true;
      setRotation(bodyfin, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 30, 0);
      tail.addBox(-1F, -1F, 0F, 2, 2, 3);
      tail.setRotationPoint(0F, 23F, 4F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 0F, 0F, 0F);
      tailfin = new ModelRenderer(this, 22, 3);
      tailfin.addBox(0F, -2.8F, 0F, 0, 2, 3);
      tailfin.setRotationPoint(0F, 23F, 4F);
      tailfin.setTextureSize(64, 32);
      tailfin.mirror = true;
      setRotation(tailfin, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    bodyfin.render(f5);
    tail.render(f5);
    tailfin.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6, Entity var7)
  {
      super.setRotationAngles(var1, var2, var3, var4, var5, var6, var7);

     
    	  this.tail.rotateAngleZ = 0F;
    	  this.head.rotateAngleZ = 0F; 
    	  this.tail.rotateAngleY = 0.2F * MathHelper.sin(var3 * (float)0.15F + var2);
    	  this.tailfin.rotateAngleZ = this.tail.rotateAngleZ;
    	  this.tailfin.rotateAngleY = this.tail.rotateAngleY;
    	  this.tailfin.rotateAngleX = this.tail.rotateAngleX;
  }

}
