//
// Date: 9/21/2014 4:22:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBothriolepis extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer LeftHeadFin;
    ModelRenderer RightHeadFin;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
  
  public ModelBothriolepis()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 6);
      Body.addBox(-3F, -1F, -2F, 4, 2, 4);
      Body.setRotationPoint(1F, 23F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      LeftHeadFin = new ModelRenderer(this, 0, 0);
      LeftHeadFin.addBox(-1F, 0F, 1F, 1, 1, 5);
      LeftHeadFin.setRotationPoint(1F, 22.5F, -2F);
      LeftHeadFin.setTextureSize(64, 32);
      LeftHeadFin.mirror = true;
      setRotation(LeftHeadFin, 0F, 0.7807508F, 0F);
      RightHeadFin = new ModelRenderer(this, 0, 0);
      RightHeadFin.addBox(0F, 0F, 1F, 1, 1, 5);
      RightHeadFin.setRotationPoint(-1F, 22.5F, -2F);
      RightHeadFin.setTextureSize(64, 32);
      RightHeadFin.mirror = true;
      setRotation(RightHeadFin, 0F, -0.7807508F, 0F);
      Tail1 = new ModelRenderer(this, 12, 6);
      Tail1.addBox(-1.5F, 0F, 1F, 3, 1, 3);
      Tail1.setRotationPoint(0F, 22.5F, 1F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 12, 2);
      Tail2.addBox(-1F, 0F, 0F, 2, 1, 3);
      Tail2.setRotationPoint(0F, 22.5F, 4F);
      Tail2.setTextureSize(64, 32);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 21, 3);
      Tail3.addBox(-0.5F, 0F, 2F, 1, 1, 6);
      Tail3.setRotationPoint(0F, 22.5F, 4F);
      Tail3.setTextureSize(64, 32);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Body.render(f5);
    LeftHeadFin.render(f5);
    RightHeadFin.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.Tail2.rotateAngleY = 0.2F * MathHelper.sin(f2 * (float)0.35F + f1);
    this.Tail3.rotateAngleY = this.Tail2.rotateAngleY;

  }

}
