// Date: 12/22/2014 4:25:54 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import org.lwjgl.opengl.GL11;

import itsabouttime.client.model.prehistoric.technical.MowzieModelBaseIAT;
import itsabouttime.client.model.prehistoric.technical.MowzieModelRenderer2;
import itsabouttime.common.entities.prehistoric.EntityCoelophysis;
import itsabouttime.common.entities.prehistoric.EntityPsittacosaurus;
import net.minecraft.entity.Entity;
import net.minecraft.entity.passive.EntitySheep;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelPsittacosaurus extends MowzieModelBaseIAT
{
	public static final float PI = (float)Math.PI;
  //fields
    MowzieModelRenderer2 LeftFoot;
    MowzieModelRenderer2 RightFoot;
    MowzieModelRenderer2 RightAnkle;
    MowzieModelRenderer2 RightLeg;
    MowzieModelRenderer2 RightHip;
    MowzieModelRenderer2 LeftAnkle;
    MowzieModelRenderer2 LeftLeg;
    MowzieModelRenderer2 LeftHip;
    MowzieModelRenderer2 Body;
    MowzieModelRenderer2 Tail1;
    MowzieModelRenderer2 Tail3;
    MowzieModelRenderer2 Tail2;
    MowzieModelRenderer2 Tail1Feathers;
    MowzieModelRenderer2 Tail2Feathers;
    MowzieModelRenderer2 Tail3Feathers;
    MowzieModelRenderer2 LeftArm;
    MowzieModelRenderer2 LeftHand;
    MowzieModelRenderer2 RightArm;
    MowzieModelRenderer2 RightHand;
    MowzieModelRenderer2 Neck;
    MowzieModelRenderer2 Head;
    MowzieModelRenderer2 BottomBeak;
    MowzieModelRenderer2 TopBeak;
    MowzieModelRenderer2 Fire;
    MowzieModelRenderer2 HeadFire;
    MowzieModelRenderer2 RightFootFire;
    MowzieModelRenderer2 LeftFootFire;
  
    private Animator animator;
  public ModelPsittacosaurus()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      LeftFoot = new MowzieModelRenderer2(this, 9, 59);
      LeftFoot.addBox(-1F, 0F, -2F, 2, 2, 3);
      LeftFoot.setRotationPoint(-3.5F, 22F, -0.5F);
      LeftFoot.setTextureSize(64, 64);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      RightFoot = new MowzieModelRenderer2(this, 9, 59);
      RightFoot.addBox(-1F, 0F, -2F, 2, 2, 3);
      RightFoot.setRotationPoint(3.5F, 22F, -0.5F);
      RightFoot.setTextureSize(64, 64);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      RightAnkle = new MowzieModelRenderer2(this, 9, 53);
      RightAnkle.addBox(-0.5F, 0F, -1F, 1, 3, 2);
      RightAnkle.setRotationPoint(3.5F, 19.6F, 0.5F);
      RightAnkle.setTextureSize(64, 64);
      RightAnkle.mirror = true;
      setRotation(RightAnkle, -0.3490659F, 0F, 0F);
      RightLeg = new MowzieModelRenderer2(this, 0, 53);
      RightLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      RightLeg.setRotationPoint(3.4F, 16.5F, -0.8F);
      RightLeg.setTextureSize(64, 64);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0.3490659F, 0F, 0F);
      RightHip = new MowzieModelRenderer2(this, 0, 45);
      RightHip.addBox(0F, -1F, -1.5F, 2, 4, 3);
      RightHip.setRotationPoint(2.5F, 14.5F, 0F);
      RightHip.setTextureSize(64, 64);
      RightHip.mirror = true;
      setRotation(RightHip, -0.3839724F, 0F, 0F);
      LeftAnkle = new MowzieModelRenderer2(this, 9, 53);
      LeftAnkle.addBox(-0.5F, 0F, -1F, 1, 3, 2);
      LeftAnkle.setRotationPoint(-3.5F, 19.6F, 0.5F);
      LeftAnkle.setTextureSize(64, 64);
      LeftAnkle.mirror = true;
      setRotation(LeftAnkle, -0.3490659F, 0F, 0F);
      LeftLeg = new MowzieModelRenderer2(this, 0, 53);
      LeftLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      LeftLeg.setRotationPoint(-3.4F, 16.5F, -0.8F);
      LeftLeg.setTextureSize(64, 64);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0.3490659F, 0F, 0F);
      LeftHip = new MowzieModelRenderer2(this, 0, 45);
      LeftHip.addBox(-2F, -1F, -1.5F, 2, 4, 3);
      LeftHip.setRotationPoint(-2.5F, 14.5F, 0F);
      LeftHip.setTextureSize(64, 64);
      LeftHip.mirror = true;
      setRotation(LeftHip, -0.3839724F, 0F, 0F);
      Body = new MowzieModelRenderer2(this, 0, 0);
      Body.addBox(-2.5F, -2.5F, -5F, 5, 5, 10);
      Body.setRotationPoint(0F, 15F, -2F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Tail1 = new MowzieModelRenderer2(this, 0, 16);
      Tail1.addBox(-2F, -2F, 0F, 4, 4, 5);
      Tail1.setRotationPoint(0F, 15F, 3F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail3 = new MowzieModelRenderer2(this, 0, 36);
      Tail3.addBox(-1F, -1F, 0F, 2, 2, 6);
      Tail3.setRotationPoint(0F, 15F, 14F);
      Tail3.setTextureSize(64, 64);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
      Tail2 = new MowzieModelRenderer2(this, 0, 26);
      Tail2.addBox(-1.5F, -1.5F, 0F, 3, 3, 6);
      Tail2.setRotationPoint(0F, 15F, 8F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Tail1Feathers = new MowzieModelRenderer2(this, 19, 16);
      Tail1Feathers.addBox(-1.5F, -4F, -2.813333F, 3, 4, 5);
      Tail1Feathers.setRotationPoint(0F, -2F, 2.8F);
      Tail1Feathers.setTextureSize(64, 64);
      Tail1Feathers.mirror = true;
      setRotation(Tail1Feathers, 0F, 0F, 0F);
      Tail2Feathers = new MowzieModelRenderer2(this, 19, 26);
      Tail2Feathers.addBox(-1F, -4.5F, -3F, 2, 4, 6);
      Tail2Feathers.setRotationPoint(0F, -1F, 3F);
      Tail2Feathers.setTextureSize(64, 64);
      Tail2Feathers.mirror = true;
      setRotation(Tail2Feathers, 0F, 0F, 0F);
      this.Tail3Feathers = new MowzieModelRenderer2(this, 17, 37);
      this.Tail3Feathers.setRotationPoint(0.0F, -1.0F, 3.0F);
      this.Tail3Feathers.addBox(-0.5F, -4.0F, -3.0F, 1, 4, 6);
      this.Tail3.addChild(this.Tail3Feathers);
      LeftArm = new MowzieModelRenderer2(this, 16, 48);
      LeftArm.addBox(-2F, -1F, -1F, 2, 4, 2);
      LeftArm.setRotationPoint(-2.5F, 16F, -5.5F);
      LeftArm.setTextureSize(64, 64);
      LeftArm.mirror = true;
      setRotation(LeftArm, 0.3490659F, 0F, 0F);
      LeftHand = new MowzieModelRenderer2(this, 25, 48);
      LeftHand.addBox(-1F, 0F, -1F, 2, 4, 2);
      LeftHand.setRotationPoint(-3.6F, 17.9F, -4.4F);
      LeftHand.setTextureSize(64, 64);
      LeftHand.mirror = true;
      setRotation(LeftHand, -0.6283185F, 0F, 0F);
      RightArm = new MowzieModelRenderer2(this, 16, 48);
      RightArm.addBox(0F, -1F, -1F, 2, 4, 2);
      RightArm.setRotationPoint(2.5F, 16F, -5.5F);
      RightArm.setTextureSize(64, 64);
      RightArm.mirror = true;
      setRotation(RightArm, 0.3490659F, 0F, 0F);
      RightHand = new MowzieModelRenderer2(this, 25, 48);
      RightHand.addBox(-1F, 0F, -1F, 2, 4, 2);
      RightHand.setRotationPoint(3.6F, 17.9F, -4.4F);
      RightHand.setTextureSize(64, 64);
      RightHand.mirror = true;
      setRotation(RightHand, -0.6283185F, 0F, 0F);
      this.Neck = new MowzieModelRenderer2(this, 21, 0);
      this.Neck.setRotationPoint(0.0F, -1.2F, -4.35F);
      this.Neck.addBox(-1.5F, -1.5F, -5.0F, 3, 3, 5);
      this.setRotation(Neck, -0.5061454830783556F, 0.0F, 0.0F);
      this.Head = new MowzieModelRenderer2(this, 38, 0);
      this.Head.setRotationPoint(0.0F, 0.0F, -4.2F);
      this.Head.addBox(-2.0F, -2.0F, -4.0F, 4, 4, 4);
      this.setRotation(Head, 0.5061454830783556F, 0.0F, 0.0F);
      this.BottomBeak = new MowzieModelRenderer2(this, 44, 9);
      this.BottomBeak.setRotationPoint(0.0F, 1.2F, -3.2F);
      this.BottomBeak.addBox(-1.0F, -0.5F, -2.0F, 2, 1, 2);
      this.setRotation(BottomBeak, -0.12217304763960307F, -0.0F, 0.0F);
      this.TopBeak = new MowzieModelRenderer2(this, 31, 9);
      this.TopBeak.setRotationPoint(0.0F, -1.0F, -3.3F);
      this.TopBeak.addBox(-1.5F, -1.0F, -3.0F, 3, 2, 3);
      this.setRotation(TopBeak, 0.5410520681182421F, -0.0F, 0.0F);
      Fire = new MowzieModelRenderer2(this, 36, 36);
      Fire.addBox(0F, -12F, -6F, 0, 14, 14);
      Fire.setRotationPoint(0F, 15F, -3F);
      Fire.setTextureSize(64, 64);
      Fire.mirror = true;
      setRotation(Fire, 0F, 0F, 0F);
      this.HeadFire = new MowzieModelRenderer2(this, 0, 55);
      this.HeadFire.setRotationPoint(0.0F, -1.4F, -3.0F);
      this.HeadFire.addBox(0.0F, -5.0F, -1.0F, 0, 5, 4);
      this.Head.addChild(this.HeadFire);
      RightFootFire = new MowzieModelRenderer2(this, 58, -3);
      RightFootFire.addBox(0F, -4F, 0F, 0, 4, 3);
      RightFootFire.setRotationPoint(4F, 22F, -2F);
      RightFootFire.setTextureSize(64, 64);
      RightFootFire.mirror = true;
      setRotation(RightFootFire, -0.3316126F, 0F, 0.3839724F);
      LeftFootFire = new MowzieModelRenderer2(this, 58, -3);
      LeftFootFire.addBox(0F, -4F, 0F, 0, 4, 3);
      LeftFootFire.setRotationPoint(-4F, 22F, -2F);
      LeftFootFire.setTextureSize(64, 64);
      LeftFootFire.mirror = true;
      setRotation(LeftFootFire, -0.3316126F, 0F, -0.3839724F);
  	animator = new Animator(this);
      this.Tail3.addChild(this.Tail3Feathers);
      this.addChildTo(Tail3,Tail2);
      this.Tail2.addChild(Tail2Feathers);
      this.addChildTo(Tail2, Tail1);
      this.Tail1.addChild(Tail1Feathers);
      this.addChildTo(Tail1,Body);

      this.addChildTo( RightFootFire,RightFoot);
      this.addChildTo( RightFoot,RightAnkle);
      this.addChildTo( RightAnkle,RightLeg);
      this.addChildTo( RightLeg,RightHip);

      this.addChildTo( LeftFootFire,LeftFoot);
      this.addChildTo( LeftFoot,LeftAnkle);
      this.addChildTo( LeftAnkle,LeftLeg);
      this.addChildTo( LeftLeg,LeftHip); 
      
      this.addChildTo(RightHand, RightArm);
      this.addChildTo(RightArm, Body);
      
      this.addChildTo(LeftHand, LeftArm);
      this.addChildTo(LeftArm, Body);
      
      this.addChildTo(Fire, Body);
      
      this.Head.addChild(TopBeak);
      this.Head.addChild(BottomBeak);
      this.Head.addChild(this.HeadFire);
      this.Neck.addChild(this.Head);
      this.Body.addChild(this.Neck);

    LeftFoot.setInitValuesToCurrentPose();
    RightFoot.setInitValuesToCurrentPose();
    RightAnkle.setInitValuesToCurrentPose();
    RightLeg.setInitValuesToCurrentPose();
    RightHip.setInitValuesToCurrentPose();
    LeftAnkle.setInitValuesToCurrentPose();
    LeftLeg.setInitValuesToCurrentPose();
    LeftHip.setInitValuesToCurrentPose();
    Body.setInitValuesToCurrentPose();
    Tail1.setInitValuesToCurrentPose();
    Tail3.setInitValuesToCurrentPose();
    Tail2.setInitValuesToCurrentPose();
    Tail1Feathers.setInitValuesToCurrentPose();
    Tail2Feathers.setInitValuesToCurrentPose();
    Tail3Feathers.setInitValuesToCurrentPose();
    LeftArm.setInitValuesToCurrentPose();
    LeftHand.setInitValuesToCurrentPose();
    RightArm.setInitValuesToCurrentPose();
    RightHand.setInitValuesToCurrentPose();
    Neck.setInitValuesToCurrentPose();
    Head.setInitValuesToCurrentPose();
    BottomBeak.setInitValuesToCurrentPose();
    TopBeak.setInitValuesToCurrentPose();
    Fire.setInitValuesToCurrentPose();
    HeadFire.setInitValuesToCurrentPose();
    RightFootFire.setInitValuesToCurrentPose();
    LeftFootFire.setInitValuesToCurrentPose();
    
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
	animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
    if (this.isChild)
    {
        float f6 = 2.0F;
        
        GL11.glPushMatrix();
        GL11.glScalef(1F / f6, 1F / f6,1F / f6);
        GL11.glTranslatef(0.0F, 24.0F * f5 , 0.0F);
    Body.render(f5);
    RightHip.render(f5);
    LeftHip.render(f5);
    GL11.glPopMatrix();}else{
        Body.render(f5);
        RightHip.render(f5);
        LeftHip.render(f5);	
    }

  }
  
  private void setRotation(MowzieModelRenderer2 model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    setAngles();
    EntityPsittacosaurus dino = (EntityPsittacosaurus) entity;
    setAngles();  
    float scaleFactor = 0.75F;
    float height = 2F * f1;
    bob(Body, 1F * scaleFactor, height, false, f, f1);
    bob(LeftHip, 1F * scaleFactor, height, false, f, f1);
    bob(RightHip, 1F * scaleFactor, height, false, f, f1);
    bob(Neck, 1F * scaleFactor, height / 2, false, f, f1);
    walk(Neck, 1F * scaleFactor, 0.25F, false, 1F, 0.4F, f, f1);
    walk(Head, 1F * scaleFactor, 0.25F, true, 1F, -0.4F, f, f1);
    walk(LeftHip, 0.5F * scaleFactor, 0.8F, false, 0F, 0.4F, f, f1);
    walk(LeftLeg, 0.5F * scaleFactor, 0.5F, true, 1F, 0F, f, f1);
    walk(LeftAnkle, 0.5F * scaleFactor, 0.5F, false, 0F, 0F, f, f1);
    walk(LeftFoot, 0.5F * scaleFactor, 1.5F, true, 0.5F, 1F, f, f1);
    walk(RightHip, 0.5F * scaleFactor, 0.8F, true, 0F, 0.4F, f, f1);
    walk(RightLeg, 0.5F * scaleFactor, 0.5F, false, 1F, 0F, f, f1);
    walk(RightAnkle, 0.5F * scaleFactor, 0.5F, true, 0F, 0F, f, f1);
    walk(RightFoot, 0.5F * scaleFactor, 1.5F, false, 0.5F, 1F, f, f1);
    faceTarget(Head, 2, f3, f4);
    faceTarget(Neck, 2, f3, f4);
    MowzieModelRenderer2[] rightArmParts = {this.RightArm, this.RightHand};
    MowzieModelRenderer2[] leftArmParts = {this.LeftArm, this.LeftHand};
    MowzieModelRenderer2[] tailParts = {this.Tail1, this.Tail2, this.Tail3};
    MowzieModelRenderer2[] NeckParts = {this.Head, this.Neck};
    tailSwing(tailParts, 1F * scaleFactor, 0.1F * f1, 2, f);
    chainWave(tailParts, 1F * scaleFactor, -0.05F, 2, f, f1);
    chainWave(rightArmParts, 1F * scaleFactor, -0.3F, 4, f, f1);
    chainWave(leftArmParts, 1F * scaleFactor, -0.3F, 4, f, f1);
    //Idling
    chainWave(NeckParts, 0.1F, -0.1F, 4, dino.frame, 1F);
    chainWave(tailParts, 0.1F, -0.05F, 2, dino.frame, 1F);
    walk(Neck, 0.1F, 0.07F, false, -1F, 0F, dino.frame, 1F);
    walk(Head, 0.1F, 0.07F, true, 0F, 0F, dino.frame, 1F);
    walk(Body, 0.1F, 0.05F, false, 0F, 0F, dino.frame, 1F);
    chainWave(rightArmParts, 0.1F, -0.1F, 4, dino.frame, 1F);
    chainWave(leftArmParts, 0.1F, -0.1F, 4, dino.frame, 1F);
    
    
    

  }
  public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		animator.update(entity);
		  setRotationAngles(f, f1, f2, f3, f4, f5, (Entity) entity);
		animator.setAnim(60);
		animator.startPhase(10);
			animator.rotate(Head, PI / 4F, 0F, 0F);
			animator.rotate(Neck, PI / 6F, 0F, 0F);
		animator.endPhase();
		animator.startPhase(10);
			animator.rotate(Head, 0F, 0F, 0F);
			animator.rotate(Neck, 0F, 0F, 0F);
		animator.endPhase();
		animator.setStationaryPhase(10);
		animator.resetPhase(0);
	}
private void setAngles() {
	LeftFoot.setCurrentPoseToInitValues();
    RightFoot.setCurrentPoseToInitValues();
    RightAnkle.setCurrentPoseToInitValues();
    RightLeg.setCurrentPoseToInitValues();
    RightHip.setCurrentPoseToInitValues();
    LeftAnkle.setCurrentPoseToInitValues();
    LeftLeg.setCurrentPoseToInitValues();
    LeftHip.setCurrentPoseToInitValues();
    Body.setCurrentPoseToInitValues();
    Tail1.setCurrentPoseToInitValues();
    Tail3.setCurrentPoseToInitValues();
    Tail2.setCurrentPoseToInitValues();
    Tail1Feathers.setCurrentPoseToInitValues();
    Tail2Feathers.setCurrentPoseToInitValues();
    Tail3Feathers.setCurrentPoseToInitValues();
    LeftArm.setCurrentPoseToInitValues();
    LeftHand.setCurrentPoseToInitValues();
    RightArm.setCurrentPoseToInitValues();
    RightHand.setCurrentPoseToInitValues();
    Neck.setCurrentPoseToInitValues();
    Head.setCurrentPoseToInitValues();
    BottomBeak.setCurrentPoseToInitValues();
    TopBeak.setCurrentPoseToInitValues();
    Fire.setCurrentPoseToInitValues();
    HeadFire.setCurrentPoseToInitValues();
    RightFootFire.setCurrentPoseToInitValues();
    LeftFootFire.setCurrentPoseToInitValues();	
}

}
