// Date: 9/6/2014 10:51:50 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHallucigenia extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer RightLeg2;
    ModelRenderer RightLeg6;
    ModelRenderer RightLeg7;
    ModelRenderer RightLeg3;
    ModelRenderer RightLeg5;
    ModelRenderer RightLeg4;
    ModelRenderer RightLeg1;
    ModelRenderer LeftLeg1;
    ModelRenderer LeftLeg7;
    ModelRenderer LeftLeg5;
    ModelRenderer LeftLeg3;
    ModelRenderer LeftLeg2;
    ModelRenderer LeftLeg6;
    ModelRenderer LeftLeg4;
    ModelRenderer HeadishThing;
    ModelRenderer Shape1;
  
  public ModelHallucigenia()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, -1F, -7F, 2, 2, 15);
      Body.setRotationPoint(-1F, 20F, 2.9F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      RightLeg2 = new ModelRenderer(this, 0, 0);
      RightLeg2.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg2.setRotationPoint(0F, 20F, -2F);
      RightLeg2.setTextureSize(64, 32);
      RightLeg2.mirror = true;
      setRotation(RightLeg2, 0F, 0F, 0.4089647F);
      RightLeg6 = new ModelRenderer(this, 0, 0);
      RightLeg6.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg6.setRotationPoint(0F, 20F, 6F);
      RightLeg6.setTextureSize(64, 32);
      RightLeg6.mirror = true;
      setRotation(RightLeg6, 0F, 0F, 0.4089647F);
      RightLeg7 = new ModelRenderer(this, 0, 0);
      RightLeg7.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg7.setRotationPoint(0F, 20F, 8F);
      RightLeg7.setTextureSize(64, 32);
      RightLeg7.mirror = true;
      setRotation(RightLeg7, 0F, 0F, 0.4089647F);
      RightLeg3 = new ModelRenderer(this, 0, 0);
      RightLeg3.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg3.setRotationPoint(0F, 20F, 0F);
      RightLeg3.setTextureSize(64, 32);
      RightLeg3.mirror = true;
      setRotation(RightLeg3, 0F, 0F, 0.4089647F);
      RightLeg5 = new ModelRenderer(this, 0, 0);
      RightLeg5.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg5.setRotationPoint(0F, 20F, 4F);
      RightLeg5.setTextureSize(64, 32);
      RightLeg5.mirror = true;
      setRotation(RightLeg5, 0F, 0F, 0.4089647F);
      RightLeg4 = new ModelRenderer(this, 0, 0);
      RightLeg4.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg4.setRotationPoint(0F, 20F, 2F);
      RightLeg4.setTextureSize(64, 32);
      RightLeg4.mirror = true;
      setRotation(RightLeg4, 0F, 0F, 0.4089647F);
      RightLeg1 = new ModelRenderer(this, 0, 0);
      RightLeg1.addBox(-1F, -4F, 0F, 1, 8, 1);
      RightLeg1.setRotationPoint(0F, 20F, -4F);
      RightLeg1.setTextureSize(64, 32);
      RightLeg1.mirror = true;
      setRotation(RightLeg1, 0F, 0F, 0.4089647F);
      LeftLeg1 = new ModelRenderer(this, 0, 0);
      LeftLeg1.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg1.setRotationPoint(0F, 20F, -4F);
      LeftLeg1.setTextureSize(64, 32);
      LeftLeg1.mirror = true;
      setRotation(LeftLeg1, 0F, 0F, -0.4089647F);
      LeftLeg7 = new ModelRenderer(this, 0, 0);
      LeftLeg7.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg7.setRotationPoint(0F, 20F, 8F);
      LeftLeg7.setTextureSize(64, 32);
      LeftLeg7.mirror = true;
      setRotation(LeftLeg7, 0F, 0F, -0.4089647F);
      LeftLeg5 = new ModelRenderer(this, 0, 0);
      LeftLeg5.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg5.setRotationPoint(0F, 20F, 4F);
      LeftLeg5.setTextureSize(64, 32);
      LeftLeg5.mirror = true;
      setRotation(LeftLeg5, 0F, 0F, -0.4089647F);
      LeftLeg3 = new ModelRenderer(this, 0, 0);
      LeftLeg3.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg3.setRotationPoint(0F, 20F, 0F);
      LeftLeg3.setTextureSize(64, 32);
      LeftLeg3.mirror = true;
      setRotation(LeftLeg3, 0F, 0F, -0.4089647F);
      LeftLeg2 = new ModelRenderer(this, 0, 0);
      LeftLeg2.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg2.setRotationPoint(0F, 20F, -2F);
      LeftLeg2.setTextureSize(64, 32);
      LeftLeg2.mirror = true;
      setRotation(LeftLeg2, 0F, 0F, -0.4089647F);
      LeftLeg6 = new ModelRenderer(this, 0, 0);
      LeftLeg6.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg6.setRotationPoint(0F, 20F, 6F);
      LeftLeg6.setTextureSize(64, 32);
      LeftLeg6.mirror = true;
      setRotation(LeftLeg6, 0F, 0F, -0.4089647F);
      LeftLeg4 = new ModelRenderer(this, 0, 0);
      LeftLeg4.addBox(0F, -4F, 0F, 1, 8, 1);
      LeftLeg4.setRotationPoint(0F, 20F, 2F);
      LeftLeg4.setTextureSize(64, 32);
      LeftLeg4.mirror = true;
      setRotation(LeftLeg4, 0F, 0F, -0.4089647F);
      HeadishThing = new ModelRenderer(this, 20, 2);
      HeadishThing.addBox(-0.5F, 0F, -3F, 1, 1, 4);
      HeadishThing.setRotationPoint(0F, 19.5F, -4F);
      HeadishThing.setTextureSize(64, 32);
      HeadishThing.mirror = true;
      setRotation(HeadishThing, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 34, 0);
      Shape1.addBox(-2.5F, -4F, 0F, 5, 7, 4);
      Shape1.setRotationPoint(0F, 20F, 10F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.1919862F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    RightLeg2.render(f5);
    RightLeg6.render(f5);
    RightLeg7.render(f5);
    RightLeg3.render(f5);
    RightLeg5.render(f5);
    RightLeg4.render(f5);
    RightLeg1.render(f5);
    LeftLeg1.render(f5);
    LeftLeg7.render(f5);
    LeftLeg5.render(f5);
    LeftLeg3.render(f5);
    LeftLeg2.render(f5);
    LeftLeg6.render(f5);
    LeftLeg4.render(f5);
    HeadishThing.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
