// Date: 9/6/2014 8:28:51 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWixwaxia extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer BackspineLeft;
    ModelRenderer BackspineRight;
  
  public ModelWixwaxia()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-1.5F, -1F, -1.5F, 3, 2, 4);
      Body.setRotationPoint(0F, 23F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);

      BackspineLeft = new ModelRenderer(this, 17, 0);
      BackspineLeft.addBox(0F, -3F, 0F, 0, 3, 4);
      BackspineLeft.setRotationPoint(-0.2F, 22F, -1.5F);
      BackspineLeft.setTextureSize(64, 32);
      BackspineLeft.mirror = true;
      setRotation(BackspineLeft, 0F, -0.296706F, 0F);
      BackspineLeft.mirror = false;
      BackspineRight = new ModelRenderer(this, 17, 0);
      BackspineRight.addBox(0.2F, -3F, 0F, 0, 3, 4);
      BackspineRight.setRotationPoint(0F, 22F, -1.5F);
      BackspineRight.setTextureSize(64, 32);
      BackspineRight.mirror = true;
      setRotation(BackspineRight, 0F, 0.296706F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    BackspineLeft.render(f5);
    BackspineRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
