// Date: 9/5/2014 5:26:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model.prehistoric;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOpabina extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Eye1;
    ModelRenderer Eye2;
    ModelRenderer Eye3;
    ModelRenderer Eye4;
    ModelRenderer Eye5;
    ModelRenderer LeftFin4;
    ModelRenderer LeftFin3;
    ModelRenderer LeftFin2;
    ModelRenderer LeftFin1;
    ModelRenderer RightFin3;
    ModelRenderer RightFin4;
    ModelRenderer RightFin2;
    ModelRenderer RightFin1;
    ModelRenderer LeftFin5;
    ModelRenderer RightFin5;
    ModelRenderer LeftFin6;
    ModelRenderer RightFin6;
    ModelRenderer RightFin7;
    ModelRenderer RightFin8;
    ModelRenderer LeftFin7;
    ModelRenderer LeftFin8;
    ModelRenderer LeftFin9;
    ModelRenderer RightFin9;
    ModelRenderer LeftFin10;
    ModelRenderer RightFin10;
    ModelRenderer TailFin;
    ModelRenderer Proboscis;
    ModelRenderer UpperJawThing;
    ModelRenderer LowerJawThing;
  
  public ModelOpabina()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 29, 0);
      Head.addBox(-3F, 0F, -7F, 7, 3, 7);
      Head.setRotationPoint(-1F, 20F, -3F);
      Head.setTextureSize(128, 64);
      Head.mirror = true;
      setRotation(Head, 0.1487144F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 13);
      Body.addBox(-3F, 0F, 0F, 7, 3, 39);
      Body.setRotationPoint(-1F, 20F, -3F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Eye1 = new ModelRenderer(this, 0, 9);
      Eye1.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye1.setRotationPoint(1F, 19F, -6F);
      Eye1.setTextureSize(128, 64);
      Eye1.mirror = true;
      setRotation(Eye1, 0F, 0F, 0F);
      Eye2 = new ModelRenderer(this, 0, 9);
      Eye2.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye2.setRotationPoint(-3F, 19F, -6F);
      Eye2.setTextureSize(128, 64);
      Eye2.mirror = true;
      setRotation(Eye2, 0F, 0F, 0F);
      Eye3 = new ModelRenderer(this, 0, 9);
      Eye3.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye3.setRotationPoint(-1F, 19F, -5F);
      Eye3.setTextureSize(128, 64);
      Eye3.mirror = true;
      setRotation(Eye3, 0F, 0F, 0F);
      Eye4 = new ModelRenderer(this, 0, 9);
      Eye4.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye4.setRotationPoint(0F, 20F, -8F);
      Eye4.setTextureSize(128, 64);
      Eye4.mirror = true;
      setRotation(Eye4, 0F, 0F, 0F);
      Eye5 = new ModelRenderer(this, 0, 9);
      Eye5.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye5.setRotationPoint(-2F, 20F, -8F);
      Eye5.setTextureSize(128, 64);
      Eye5.mirror = true;
      setRotation(Eye5, 0F, 0F, 0F);
      LeftFin4 = new ModelRenderer(this, 0, 39);
      LeftFin4.addBox(0F, 0F, -2F, 8, 1, 4);
      LeftFin4.setRotationPoint(3F, 20F, 9F);
      LeftFin4.setTextureSize(128, 64);
      LeftFin4.mirror = true;
      setRotation(LeftFin4, 0F, 0F, 0F);
      LeftFin3 = new ModelRenderer(this, 0, 34);
      LeftFin3.addBox(0F, 0F, -2F, 7, 1, 4);
      LeftFin3.setRotationPoint(3F, 20F, 5F);
      LeftFin3.setTextureSize(128, 64);
      LeftFin3.mirror = true;
      setRotation(LeftFin3, 0F, 0F, 0F);
      LeftFin2 = new ModelRenderer(this, 0, 29);
      LeftFin2.addBox(0F, 0F, -2F, 6, 1, 4);
      LeftFin2.setRotationPoint(3F, 20F, 1F);
      LeftFin2.setTextureSize(128, 64);
      LeftFin2.mirror = true;
      setRotation(LeftFin2, 0F, 0F, 0F);
      LeftFin1 = new ModelRenderer(this, 0, 24);
      LeftFin1.addBox(0F, 0F, -2F, 5, 1, 4);
      LeftFin1.setRotationPoint(3F, 20F, -3F);
      LeftFin1.setTextureSize(128, 64);
      LeftFin1.mirror = true;
      setRotation(LeftFin1, 0F, 0F, 0F);
      RightFin3 = new ModelRenderer(this, 0, 34);
      RightFin3.addBox(-7F, 0F, -2F, 7, 1, 4);
      RightFin3.setRotationPoint(-4F, 20F, 5F);
      RightFin3.setTextureSize(128, 64);
      RightFin3.mirror = true;
      setRotation(RightFin3, 0F, 0F, 0F);
      RightFin4 = new ModelRenderer(this, 0, 39);
      RightFin4.addBox(-8F, 0F, -2F, 8, 1, 4);
      RightFin4.setRotationPoint(-4F, 20F, 9F);
      RightFin4.setTextureSize(128, 64);
      RightFin4.mirror = true;
      setRotation(RightFin4, 0F, 0F, 0F);
      RightFin2 = new ModelRenderer(this, 0, 29);
      RightFin2.addBox(-6F, 0F, -2F, 6, 1, 4);
      RightFin2.setRotationPoint(-4F, 20F, 1F);
      RightFin2.setTextureSize(128, 64);
      RightFin2.mirror = true;
      setRotation(RightFin2, 0F, 0F, 0F);
      RightFin1 = new ModelRenderer(this, 0, 24);
      RightFin1.addBox(-5F, 0F, -2F, 5, 1, 4);
      RightFin1.setRotationPoint(-4F, 20F, -3F);
      RightFin1.setTextureSize(128, 64);
      RightFin1.mirror = true;
      setRotation(RightFin1, 0F, 0F, 0F);
      LeftFin5 = new ModelRenderer(this, 0, 39);
      LeftFin5.addBox(0F, 0F, -2F, 8, 1, 4);
      LeftFin5.setRotationPoint(3F, 20F, 13F);
      LeftFin5.setTextureSize(128, 64);
      LeftFin5.mirror = true;
      setRotation(LeftFin5, 0F, 0F, 0F);
      RightFin5 = new ModelRenderer(this, 0, 39);
      RightFin5.addBox(-8F, 0F, -2F, 8, 1, 4);
      RightFin5.setRotationPoint(-4F, 20F, 13F);
      RightFin5.setTextureSize(128, 64);
      RightFin5.mirror = true;
      setRotation(RightFin5, 0F, 0F, 0F);
      LeftFin6 = new ModelRenderer(this, 0, 34);
      LeftFin6.addBox(0F, 0F, -2F, 7, 1, 4);
      LeftFin6.setRotationPoint(3F, 20F, 17F);
      LeftFin6.setTextureSize(128, 64);
      LeftFin6.mirror = true;
      setRotation(LeftFin6, 0F, 0F, 0F);
      RightFin6 = new ModelRenderer(this, 0, 34);
      RightFin6.addBox(-7F, 0F, -2F, 7, 1, 4);
      RightFin6.setRotationPoint(-4F, 20F, 17F);
      RightFin6.setTextureSize(128, 64);
      RightFin6.mirror = true;
      setRotation(RightFin6, 0F, 0F, 0F);
      RightFin7 = new ModelRenderer(this, 0, 29);
      RightFin7.addBox(-6F, 0F, -2F, 6, 1, 4);
      RightFin7.setRotationPoint(-4F, 20F, 21F);
      RightFin7.setTextureSize(128, 64);
      RightFin7.mirror = true;
      setRotation(RightFin7, 0F, 0F, 0F);
      RightFin8 = new ModelRenderer(this, 0, 24);
      RightFin8.addBox(-5F, 0F, -2F, 5, 1, 4);
      RightFin8.setRotationPoint(-4F, 20F, 25F);
      RightFin8.setTextureSize(128, 64);
      RightFin8.mirror = true;
      setRotation(RightFin8, 0F, 0F, 0F);
      LeftFin7 = new ModelRenderer(this, 0, 29);
      LeftFin7.addBox(0F, 0F, -2F, 6, 1, 4);
      LeftFin7.setRotationPoint(3F, 20F, 21F);
      LeftFin7.setTextureSize(128, 64);
      LeftFin7.mirror = true;
      setRotation(LeftFin7, 0F, 0F, 0F);
      LeftFin8 = new ModelRenderer(this, 0, 24);
      LeftFin8.addBox(0F, 0F, -2F, 5, 1, 4);
      LeftFin8.setRotationPoint(3F, 20F, 25F);
      LeftFin8.setTextureSize(128, 64);
      LeftFin8.mirror = true;
      setRotation(LeftFin8, 0F, 0F, 0F);
      LeftFin9 = new ModelRenderer(this, 0, 44);
      LeftFin9.addBox(0F, 0F, -2F, 4, 1, 4);
      LeftFin9.setRotationPoint(3F, 20F, 29F);
      LeftFin9.setTextureSize(128, 64);
      LeftFin9.mirror = true;
      setRotation(LeftFin9, 0F, 0F, 0F);
      RightFin9 = new ModelRenderer(this, 0, 44);
      RightFin9.addBox(-4F, 0F, -2F, 4, 1, 4);
      RightFin9.setRotationPoint(-4F, 20F, 29F);
      RightFin9.setTextureSize(128, 64);
      RightFin9.mirror = true;
      setRotation(RightFin9, 0F, 0F, 0F);
      LeftFin10 = new ModelRenderer(this, 16, 44);
      LeftFin10.addBox(0F, 0F, -2F, 3, 1, 4);
      LeftFin10.setRotationPoint(3F, 20F, 33F);
      LeftFin10.setTextureSize(128, 64);
      LeftFin10.mirror = true;
      setRotation(LeftFin10, 0F, 0F, 0F);
      RightFin10 = new ModelRenderer(this, 16, 44);
      RightFin10.addBox(-3F, 0F, -2F, 3, 1, 4);
      RightFin10.setRotationPoint(-4F, 20F, 33F);
      RightFin10.setTextureSize(128, 64);
      RightFin10.mirror = true;
      setRotation(RightFin10, 0F, 0F, 0F);
      TailFin = new ModelRenderer(this, 0, 0);
      TailFin.addBox(-4F, 0F, 0F, 9, 1, 5);
      TailFin.setRotationPoint(-1F, 20F, 35F);
      TailFin.setTextureSize(128, 64);
      TailFin.mirror = true;
      setRotation(TailFin, 0F, 0F, 0F);
      Proboscis = new ModelRenderer(this, 0, 14);
      Proboscis.addBox(-0.5F, 0F, -8F, 1, 1, 9);
      Proboscis.setRotationPoint(-0.5F, 22F, -10F);
      Proboscis.setTextureSize(128, 64);
      Proboscis.mirror = true;
      setRotation(Proboscis, 0F, 0F, 0F);
      UpperJawThing = new ModelRenderer(this, 0, 18);
      UpperJawThing.addBox(-0.5F, 2F, -9F, 1, 1, 2);
      UpperJawThing.setRotationPoint(-0.5F, 22F, -10F);
      UpperJawThing.setTextureSize(128, 64);
      UpperJawThing.mirror = true;
      setRotation(UpperJawThing, -0.2974289F, 0F, 0F);
      LowerJawThing = new ModelRenderer(this, 0, 15);
      LowerJawThing.addBox(-0.5F, -2F, -9F, 1, 1, 2);
      LowerJawThing.setRotationPoint(-0.5F, 22F, -10F);
      LowerJawThing.setTextureSize(128, 64);
      LowerJawThing.mirror = true;
      setRotation(LowerJawThing, 0.2974289F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    Body.render(f5);
    Eye1.render(f5);
    Eye2.render(f5);
    Eye3.render(f5);
    Eye4.render(f5);
    Eye5.render(f5);
    LeftFin4.render(f5);
    LeftFin3.render(f5);
    LeftFin2.render(f5);
    LeftFin1.render(f5);
    RightFin3.render(f5);
    RightFin4.render(f5);
    RightFin2.render(f5);
    RightFin1.render(f5);
    LeftFin5.render(f5);
    RightFin5.render(f5);
    LeftFin6.render(f5);
    RightFin6.render(f5);
    RightFin7.render(f5);
    RightFin8.render(f5);
    LeftFin7.render(f5);
    LeftFin8.render(f5);
    LeftFin9.render(f5);
    RightFin9.render(f5);
    LeftFin10.render(f5);
    RightFin10.render(f5);
    TailFin.render(f5);
    Proboscis.render(f5);
    UpperJawThing.render(f5);
    LowerJawThing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
