// Date: 10/12/2014 1:53:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model;

import itsabouttime.common.entities.EntityTimeMachine;
import itsabouttime.common.entities.prehistoric.EntityVelociraptor;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

public class ModelTimeMachine extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer chairbase;
    ModelRenderer frontbase;
    ModelRenderer leftpole1;
    ModelRenderer frontpole;
    ModelRenderer controlpanel;
    ModelRenderer panelbar;
    ModelRenderer leftbar1;
    ModelRenderer rightbar1;
    ModelRenderer backcircle;
    ModelRenderer chairseat;
    ModelRenderer rightpole1;
    ModelRenderer circleconnector1;
    ModelRenderer leftbar2;
    ModelRenderer rightpole2;
    ModelRenderer rightbar2;
    ModelRenderer chairheadrest;
    ModelRenderer leftpole2;
    ModelRenderer backbar;
    ModelRenderer backpole;
    ModelRenderer backplate;
  
  public ModelTimeMachine()
  {
    textureWidth = 512;
    textureHeight = 512;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-10F, 0F, -10F, 20, 3, 30);
      base.setRotationPoint(0F, 21F, 0F);
      base.setTextureSize(512, 512);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      chairbase = new ModelRenderer(this, 109, 0);
      chairbase.addBox(-5F, -3F, -1F, 10, 3, 13);
      chairbase.setRotationPoint(0F, 21F, 0F);
      chairbase.setTextureSize(512, 512);
      chairbase.mirror = true;
      setRotation(chairbase, 0F, 0F, 0F);
      frontbase = new ModelRenderer(this, 0, 46);
      frontbase.addBox(0F, -1F, 0F, 14, 3, 14);
      frontbase.setRotationPoint(0F, 22.1F, -20F);
      frontbase.setTextureSize(512, 512);
      frontbase.mirror = true;
      setRotation(frontbase, 0F, -0.7853982F, 0F);
      leftpole1 = new ModelRenderer(this, 0, 72);
      leftpole1.addBox(-1F, 0F, -1F, 2, 10, 2);
      leftpole1.setRotationPoint(8F, 11F, -9F);
      leftpole1.setTextureSize(512, 512);
      leftpole1.mirror = true;
      setRotation(leftpole1, 0F, 0F, 0F);
      frontpole = new ModelRenderer(this, 0, 72);
      frontpole.addBox(-1F, 0F, -1F, 2, 11, 2);
      frontpole.setRotationPoint(0F, 10.9F, -18F);
      frontpole.setTextureSize(512, 512);
      frontpole.mirror = true;
      setRotation(frontpole, 0F, 0.7853982F, 0F);
      controlpanel = new ModelRenderer(this, 12, 90);
      controlpanel.addBox(-5F, -1F, -1F, 10, 4, 4);
      controlpanel.setRotationPoint(0F, 10.5F, -9F);
      controlpanel.setTextureSize(512, 512);
      controlpanel.mirror = true;
      setRotation(controlpanel, -0.7853982F, 0F, 0F);
      panelbar = new ModelRenderer(this, 160, 0);
      panelbar.addBox(-7F, 0F, -1F, 14, 2, 2);
      panelbar.setRotationPoint(0F, 11F, -9F);
      panelbar.setTextureSize(512, 512);
      panelbar.mirror = true;
      setRotation(panelbar, 0F, 0F, 0F);
      leftbar1 = new ModelRenderer(this, 160, 9);
      leftbar1.addBox(1F, -1F, -1F, 13, 2, 2);
      leftbar1.setRotationPoint(0F, 11.9F, -18F);
      leftbar1.setTextureSize(512, 512);
      leftbar1.mirror = true;
      setRotation(leftbar1, 0F, -0.7853982F, 0F);
      rightbar1 = new ModelRenderer(this, 160, 9);
      rightbar1.addBox(-14F, -1F, -1F, 13, 2, 2);
      rightbar1.setRotationPoint(0F, 11.9F, -18F);
      rightbar1.setTextureSize(512, 512);
      rightbar1.mirror = true;
      setRotation(rightbar1, 0F, 0.7853982F, 0F);
      backcircle = new ModelRenderer(this, 0, 106);
      backcircle.addBox(-8F, -8F, 0F, 16, 16, 4);
      backcircle.setRotationPoint(0F, 12F, 21F);
      backcircle.setTextureSize(512, 512);
      backcircle.mirror = true;
      setRotation(backcircle, 0F, 0F, -0.7853982F);
      chairseat = new ModelRenderer(this, 109, 20);
      chairseat.addBox(-5F, -7F, -1F, 10, 4, 9);
      chairseat.setRotationPoint(0F, 21F, 0F);
      chairseat.setTextureSize(512, 512);
      chairseat.mirror = true;
      setRotation(chairseat, 0F, 0F, 0F);
      rightpole1 = new ModelRenderer(this, 0, 72);
      rightpole1.addBox(-1F, 0F, -1F, 2, 10, 2);
      rightpole1.setRotationPoint(-8F, 11F, -9F);
      rightpole1.setTextureSize(512, 512);
      rightpole1.mirror = true;
      setRotation(rightpole1, 0F, 0F, 0F);
      circleconnector1 = new ModelRenderer(this, 201, 0);
      circleconnector1.addBox(-1.5F, -8F, -1.5F, 3, 8, 3);
      circleconnector1.setRotationPoint(0F, 12F, 13F);
      circleconnector1.setTextureSize(512, 512);
      circleconnector1.mirror = true;
      setRotation(circleconnector1, -1.570796F, 0F, 0F);
      leftbar2 = new ModelRenderer(this, 160, 18);
      leftbar2.addBox(-1F, -1F, -1F, 2, 2, 20);
      leftbar2.setRotationPoint(8F, 12F, -7F);
      leftbar2.setTextureSize(512, 512);
      leftbar2.mirror = true;
      setRotation(leftbar2, 0F, 0F, 0F);
      rightpole2 = new ModelRenderer(this, 0, 72);
      rightpole2.addBox(-1F, 0F, -1F, 2, 10, 2);
      rightpole2.setRotationPoint(-8F, 11F, 13F);
      rightpole2.setTextureSize(512, 512);
      rightpole2.mirror = true;
      setRotation(rightpole2, 0F, 0F, 0F);
      rightbar2 = new ModelRenderer(this, 160, 18);
      rightbar2.addBox(-1F, -1F, -1F, 2, 2, 20);
      rightbar2.setRotationPoint(-8F, 12F, -7F);
      rightbar2.setTextureSize(512, 512);
      rightbar2.mirror = true;
      setRotation(rightbar2, 0F, 0F, 0F);
      chairheadrest = new ModelRenderer(this, 110, 45);
      chairheadrest.addBox(-5F, -16F, -1F, 10, 16, 4);
      chairheadrest.setRotationPoint(0F, 18F, 9F);
      chairheadrest.setTextureSize(512, 512);
      chairheadrest.mirror = true;
      setRotation(chairheadrest, 0F, 0F, 0F);
      leftpole2 = new ModelRenderer(this, 0, 72);
      leftpole2.addBox(-1F, 0F, -1F, 2, 10, 2);
      leftpole2.setRotationPoint(8F, 11F, 13F);
      leftpole2.setTextureSize(512, 512);
      leftpole2.mirror = true;
      setRotation(leftpole2, 0F, 0F, 0F);
      backbar = new ModelRenderer(this, 160, 44);
      backbar.addBox(-1F, 0F, -1F, 14, 2, 2);
      backbar.setRotationPoint(-6F, 11F, 13F);
      backbar.setTextureSize(512, 512);
      backbar.mirror = true;
      setRotation(backbar, 0F, 0F, 0F);
      backpole = new ModelRenderer(this, 0, 87);
      backpole.addBox(-1F, 0F, -1F, 2, 11, 2);
      backpole.setRotationPoint(0F, 12F, 18F);
      backpole.setTextureSize(512, 512);
      backpole.mirror = true;
      setRotation(backpole, 0F, 0F, 0F);
      backplate = new ModelRenderer(this, 17, 67);
      backplate.addBox(-6F, 0F, -1F, 12, 11, 2);
      backplate.setRotationPoint(0F, 12F, 13F);
      backplate.setTextureSize(512, 512);
      backplate.mirror = true;
      setRotation(backplate, 0.5235988F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
   

    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    GL11.glPushMatrix();
    GL11.glTranslatef(0, 0, -0.4F);
    base.render(f5);
    chairbase.render(f5);
    frontbase.render(f5);
    leftpole1.render(f5);
    frontpole.render(f5);
    controlpanel.render(f5);
    panelbar.render(f5);
    leftbar1.render(f5);
    rightbar1.render(f5);
    backcircle.render(f5);
    chairseat.render(f5);
    rightpole1.render(f5);
    circleconnector1.render(f5);
    leftbar2.render(f5);
    rightpole2.render(f5);
    rightbar2.render(f5);
    chairheadrest.render(f5);
    leftpole2.render(f5);
    backbar.render(f5);
    backpole.render(f5);
    backplate.render(f5);
    GL11.glPopMatrix();
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  public void setLivingAnimations(EntityLivingBase p_78086_1_, float p_78086_2_, float p_78086_3_, float p_78086_4_)
  {
      EntityTimeMachine entitywolf = (EntityTimeMachine)p_78086_1_;

      



  	
   }

 
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
