// Date: 11/16/2014 4:32:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package itsabouttime.client.model;

import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTest extends ModelBase
{
	public static final float PI = (float)Math.PI;
	private Animator animator;
  //fields
    ModelRenderer body;
    ModelRenderer head;
  
  public ModelTest()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 32, 0);
      body.addBox(-3F, 0F, -3F, 6, 11, 6);
      body.setRotationPoint(0F, 13F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 13F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      
      this.convertToChild(body, head);
      
	  animator = new Animator(this);

  }
  protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild)
  {
     // move child rotation point to be relative to parent
     parChild.rotationPointX -= parParent.rotationPointX;
     parChild.rotationPointY -= parParent.rotationPointY;
     parChild.rotationPointZ -= parParent.rotationPointZ;
     // make rotations relative to parent
     parChild.rotateAngleX -= parParent.rotateAngleX;
     parChild.rotateAngleY -= parParent.rotateAngleY;
     parChild.rotateAngleZ -= parParent.rotateAngleZ;
     // create relationship
     parParent.addChild(parChild);
  } 
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
    body.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setAngles() {
	  body.rotationPointY=13F;
	}
	
	public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		animator.update(entity);
		setAngles();
		
		animator.setAnim(2);
		//5s
		animator.startPhase(100);
		animator.rotate(head, -PI / 6F, 0F, 0F);
		animator.rotate(body, -PI / 6F, 0F, 0F);
		//end the phase
		animator.endPhase();
		//5s
		animator.startPhase(50);
		animator.rotate(head, PI / 2F, 0F, 0F);
		//end the phase
		animator.endPhase();
	}//PI=180
}
