// Date: 1/29/2015 4:34:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package iat.client.models.blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

public class ModelCleaningTable extends ModelBase
{
	//fields
	ModelRenderer RightBackLeg;
	ModelRenderer RightFrontLeg;
	ModelRenderer LeftFrontLeg;
	ModelRenderer LeftBackLeg;
	ModelRenderer Water;
	ModelRenderer FrontPanel;
	ModelRenderer BackPanel;
	ModelRenderer RightPanel;
	ModelRenderer LeftPanel;
	ModelRenderer BucketBottom;
	ModelRenderer BucketFront;
	ModelRenderer BucketBack;
	ModelRenderer BucketLeft;
	ModelRenderer BucketRight;
	ModelRenderer Wood;

	public ModelCleaningTable()
	{
		textureWidth = 64;
		textureHeight = 32;

		RightBackLeg = new ModelRenderer(this, 0, 11);
		RightBackLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		RightBackLeg.setRotationPoint(-6F, 14F, 6F);
		RightBackLeg.setTextureSize(64, 32);
		RightBackLeg.mirror = true;
		setRotation(RightBackLeg, 0F, 0F, 0F);
		RightFrontLeg = new ModelRenderer(this, 0, 11);
		RightFrontLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		RightFrontLeg.setRotationPoint(-6F, 14F, -6F);
		RightFrontLeg.setTextureSize(64, 32);
		RightFrontLeg.mirror = true;
		setRotation(RightFrontLeg, 0F, 0F, 0F);
		LeftFrontLeg = new ModelRenderer(this, 0, 11);
		LeftFrontLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		LeftFrontLeg.setRotationPoint(6F, 14F, -6F);
		LeftFrontLeg.setTextureSize(64, 32);
		LeftFrontLeg.mirror = true;
		setRotation(LeftFrontLeg, 0F, 0F, 0F);
		LeftBackLeg = new ModelRenderer(this, 0, 11);
		LeftBackLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		LeftBackLeg.setRotationPoint(6F, 14F, 6F);
		LeftBackLeg.setTextureSize(64, 32);
		LeftBackLeg.mirror = true;
		setRotation(LeftBackLeg, 0F, 0F, 0F);
		Water = new ModelRenderer(this, 46, 0);
		Water.addBox(-3F, 0F, -3F, 6, 0, 6);
		Water.setRotationPoint(0F, 14F, 0F);
		Water.setTextureSize(64, 32);
		Water.mirror = true;
		setRotation(Water, 0F, 0F, 0F);
		FrontPanel = new ModelRenderer(this, 22, 13);
		FrontPanel.addBox(-8F, -1F, -5F, 16, 1, 5);
		FrontPanel.setRotationPoint(0F, 14F, -3F);
		FrontPanel.setTextureSize(64, 32);
		FrontPanel.mirror = true;
		setRotation(FrontPanel, 0F, 0F, 0F);
		BackPanel = new ModelRenderer(this, 22, 13);
		BackPanel.addBox(-8F, -1F, 0F, 16, 1, 5);
		BackPanel.setRotationPoint(0F, 14F, 3F);
		BackPanel.setTextureSize(64, 32);
		BackPanel.mirror = true;
		setRotation(BackPanel, 0F, 0F, 0F);
		RightPanel = new ModelRenderer(this, 42, 6);
		RightPanel.addBox(-5F, 0F, -3F, 5, 1, 6);
		RightPanel.setRotationPoint(-3F, 13F, 0F);
		RightPanel.setTextureSize(64, 32);
		RightPanel.mirror = true;
		setRotation(RightPanel, 0F, 0F, 0F);
		LeftPanel = new ModelRenderer(this, 42, 6);
		LeftPanel.addBox(0F, 0F, -3F, 5, 1, 6);
		LeftPanel.setRotationPoint(3F, 13F, 0F);
		LeftPanel.setTextureSize(64, 32);
		LeftPanel.mirror = true;
		setRotation(LeftPanel, 0F, 0F, 0F);
		BucketBottom = new ModelRenderer(this, 22, 19);
		BucketBottom.addBox(-4F, 1F, -4F, 8, 1, 8);
		BucketBottom.setRotationPoint(0F, 18F, 0F);
		BucketBottom.setTextureSize(64, 32);
		BucketBottom.mirror = true;
		setRotation(BucketBottom, 0F, 0F, 0F);
		BucketFront = new ModelRenderer(this, 33, 0);
		BucketFront.addBox(-4F, 0F, -1F, 8, 5, 1);
		BucketFront.setRotationPoint(0F, 14F, -3F);
		BucketFront.setTextureSize(64, 32);
		BucketFront.mirror = true;
		setRotation(BucketFront, 0F, 0F, 0F);
		BucketBack = new ModelRenderer(this, 33, 0);
		BucketBack.addBox(-4F, 0F, 0F, 8, 5, 1);
		BucketBack.setRotationPoint(0F, 14F, 3F);
		BucketBack.setTextureSize(64, 32);
		BucketBack.mirror = true;
		setRotation(BucketBack, 0F, 0F, 0F);
		BucketLeft = new ModelRenderer(this, 8, 11);
		BucketLeft.addBox(0F, 0F, -3F, 1, 5, 6);
		BucketLeft.setRotationPoint(3F, 14F, 0F);
		BucketLeft.setTextureSize(64, 32);
		BucketLeft.mirror = true;
		setRotation(BucketLeft, 0F, 0F, 0F);
		BucketRight = new ModelRenderer(this, 8, 11);
		BucketRight.addBox(-1F, 0F, -3F, 1, 5, 6);
		BucketRight.setRotationPoint(-3F, 14F, 0F);
		BucketRight.setTextureSize(64, 32);
		BucketRight.mirror = true;
		setRotation(BucketRight, 0F, 0F, 0F);
		Wood = new ModelRenderer(this, 0, 0);
		Wood.addBox(-3.5F, 0F, -3.5F, 7, 4, 7);
		Wood.setRotationPoint(0F, 20F, 0F);
		Wood.setTextureSize(64, 32);
		Wood.mirror = true;
		setRotation(Wood, 0F, 0F, 0F);
	}

	public void render(float f5)
	{
		RightBackLeg.render(f5);
		RightFrontLeg.render(f5);
		LeftFrontLeg.render(f5);
		LeftBackLeg.render(f5);
		FrontPanel.render(f5);
		BackPanel.render(f5);
		RightPanel.render(f5);
		LeftPanel.render(f5);
		BucketBottom.render(f5);
		BucketFront.render(f5);
		BucketBack.render(f5);
		BucketLeft.render(f5);
		BucketRight.render(f5);
		Wood.render(f5);
		GL11.glEnable(GL11.GL_BLEND);
		GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
		Water.render(f5);
		GL11.glDisable(GL11.GL_BLEND);

	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}


}
